"""Added image option

Revision ID: 613a077a0046
Revises: fb9827e6299c
Create Date: 2022-10-10 18:34:02.443168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613a077a0046'
down_revision = 'fb9827e6299c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
