"""Initial migration.

Revision ID: fb9827e6299c
Revises: bb340e424594
Create Date: 2022-10-09 17:24:23.409114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9827e6299c'
down_revision = 'bb340e424594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories_name', sa.String(length=100), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_categories_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.drop_table('subjects')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=100), nullable=False))
        batch_op.drop_column('subjects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('categories')

    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subjects_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('categories')
    # ### end Alembic commands ###
